[config]
default_to_workspace = false

[env]
DEV_ENV_FILE = ".env.dev"
DEV_COMPOSE_FILE = "compose.dev.yml"

[tasks.db-up]
command = "docker"
args = [
    "compose",
    "--env-file",
    "${DEV_ENV_FILE}",
    "-f",
    "${DEV_COMPOSE_FILE}",
    "up",
    "-d",
    "--wait",
    "postgres",
]

[tasks.db-down]
command = "docker"
args = [
    "compose",
    "--env-file",
    "${DEV_ENV_FILE}",
    "-f",
    "${DEV_COMPOSE_FILE}",
    "down",
]

[tasks.backend]
dependencies = ["db-up"]
env_files = ["${DEV_ENV_FILE}"]
command = "cargo"
args = ["run", "-p", "backend"]

[tasks.db-migrate]
dependencies = ["db-up"]
env_files = ["${DEV_ENV_FILE}"]
command = "./scripts/sqlx.sh"
args = ["migrate", "run", "--source", "backend/migrations"]

[tasks.sqlx-check]
dependencies = ["db-migrate"]
run_task = { name = "sqlx-check-inner", fork = true, cleanup_task = "db-down"}

[tasks.sqlx-check-inner]
private = true
env_files = ["${DEV_ENV_FILE}"]
command = "./scripts/sqlx.sh"
args = ["prepare", "--workspace", "--check", "--", "--all-targets", "--all-features"]

[tasks.sqlx-prepare]
dependencies = ["db-migrate"]
run_task = { name = "sqlx-prepare-inner", fork = true, cleanup_task = "db-down"}

[tasks.sqlx-prepare-inner]
private = true
env_files = ["${DEV_ENV_FILE}"]
command = "./scripts/sqlx.sh"
args = ["prepare", "--workspace", "--", "--all-targets", "--all-features"]

[tasks.rust-check]
env = { SQLX_OFFLINE = "true" }
command = "cargo"
args = ["clippy", "-p", "backend", "--all-targets", "--all-features", "--", "-D", "warnings"]

